/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public String getGreeting() {
        return "binary tree demonstration";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Squirrel cheeks = new Squirrel("Cheeks");
        Node nodeOne = new Node(cheeks);

        Squirrel squeaks = new Squirrel("Squeaks");
        Node nodeTwo = new Node(squeaks);

        Squirrel fluffybutt = new Squirrel("Mr. Fluffy Butt");
        Node nodeThree = new Node(fluffybutt);

        nodeOne.set_left(nodeTwo);
        nodeOne.set_right(nodeThree);

        Node retrievedLeft = nodeOne.left(); // This should retrieve the left node
        Node retrievedRight = nodeOne.right(); // This should retrieve the right node


    }
}
